#!/usr/bin/env node
// Imagery coverage report: which terms have images, which have none, and
// where the open-license gaps fall by era. Writes harvest/COVERAGE.md.
// Usage: node scripts/coverage-report.js

import { writeFileSync } from "node:fs";
import { loadContentDir } from "./lib/load.js";

const { entries, errors } = loadContentDir("content");
if (errors.length) {
  errors.forEach((e) => console.error(e));
  process.exit(1);
}

const rows = entries.map(({ doc }) => {
  const images = doc.images ?? [];
  const open = images.filter((i) => i.rights_status === "open").length;
  const restricted = images.filter(
    (i) => i.rights_status === "restricted",
  ).length;
  const unknown = images.length - open - restricted;
  const approved = images.filter((i) => i.review_status === "approved").length;
  const rejected = images.filter((i) => i.review_status === "rejected").length;
  const pending = images.length - approved - rejected;
  const periods = doc.facets?.era?.periods ?? [];
  const origin = periods.find((p) => p.role === "origin");
  return {
    id: doc.id,
    type: doc.term_type,
    name: doc.names.primary,
    total: images.length,
    open,
    restricted,
    unknown,
    approved,
    pending,
    rejected,
    guide: Boolean(doc.guide),
    summary: Boolean(doc.summary),
    startYear: origin?.start_year ?? null,
    eraKnown: periods.length > 0,
  };
});

const eraBucket = (y) => {
  if (y === null) return "era unknown (harvest gap)";
  if (y < 1800) return "pre-1800";
  if (y < 1900) return "1800–1899";
  if (y < 1945) return "1900–1944";
  if (y < 1980) return "1945–1979";
  if (y < 2000) return "1980–1999";
  return "2000–present";
};

const lines = [];
lines.push("# Imagery coverage report");
lines.push("");
lines.push(`Generated by \`scripts/coverage-report.js\`. Do not edit by hand.`);
lines.push("");
lines.push(
  `**${rows.length} entries · ${rows.filter((r) => r.guide).length} practical guides · ${rows.filter((r) => r.summary).length} sourced overviews · ${rows.filter((r) => r.eraKnown).length} dated entries.**`,
);
lines.push("");
lines.push(
  "Only approved images appear on the site. Licensing and visual relevance are separate checks; a large harvest does not mean a well-illustrated reference.",
);
lines.push("");
lines.push("## Per term");
lines.push("");
lines.push(
  "| Term | Type | Images | Approved | Pending | Rejected | Open | Restricted | Unknown |",
);
lines.push("|---|---|---:|---:|---:|---:|---:|---:|---:|");
for (const r of [...rows].sort(
  (a, b) => a.total - b.total || a.id.localeCompare(b.id),
)) {
  lines.push(
    `| ${r.name} | ${r.type} | ${r.total} | ${r.approved} | ${r.pending} | ${r.rejected} | ${r.open} | ${r.restricted} | ${r.unknown} |`,
  );
}
lines.push("");

const none = rows.filter((r) => r.total === 0);
const noOpen = rows.filter((r) => r.total > 0 && r.open === 0);
lines.push("## Gaps");
lines.push("");
lines.push(
  `- **No approved representative image:** ${
    rows
      .filter((r) => !r.approved)
      .map((r) => r.name)
      .join(", ") || "none"
  }`,
);
lines.push(
  `- **No imagery at all:** ${none.length ? none.map((r) => r.name).join(", ") : "none"}`,
);
lines.push(
  `- **Imagery but nothing openly licensed:** ${noOpen.length ? noOpen.map((r) => r.name).join(", ") : "none"}`,
);
lines.push("");

lines.push("## Open-license coverage by era (origin period)");
lines.push("");
const buckets = new Map();
for (const r of rows) {
  const b = eraBucket(r.startYear);
  if (!buckets.has(b)) buckets.set(b, []);
  buckets.get(b).push(r);
}
lines.push("| Era | Terms | With open imagery | Open images total |");
lines.push("|---|---|---:|---:|");
for (const [era, list] of [...buckets.entries()].sort()) {
  const withOpen = list.filter((r) => r.open > 0).length;
  const openTotal = list.reduce((s, r) => s + r.open, 0);
  lines.push(
    `| ${era} | ${list.map((r) => r.name).join(", ")} | ${withOpen}/${list.length} | ${openTotal} |`,
  );
}
lines.push("");
lines.push("## Source notes");
lines.push("");
lines.push("- Wikimedia Commons: open licenses only, downloaded locally.");
lines.push("- V&A: restricted (V&A non-commercial terms), hotlinked via IIIF.");
lines.push(
  "- MoMA dataset: metadata CC0, image rights not cleared — restricted, hotlinked.",
);
lines.push(
  "- Cooper Hewitt: **blocked — needs an API access token** (api.collection.cooperhewitt.org rejects keyless calls).",
);
lines.push(
  "- Rijksmuseum: **blocked — legacy API retired (HTTP 410); new API needs a key.**",
);
lines.push("");

const out = lines.join("\n");
writeFileSync("harvest/COVERAGE.md", out);
console.log(out);
console.log("→ written to harvest/COVERAGE.md");
